[build-system]
requires = [
    "setuptools",
    "wheel",
    "attr",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv]
# use develop install to avoid rebuilding the world
usedevelop = True

deps =
    discover

commands =
    python setup.py --quiet install
    discover -p "*.py" -s python/tests
"""
