[build-system]
requires = [
    "setuptools",
    "wheel",
    "attr",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv]
# skip install to avoid rebuilding the world, do the install with setup.py
# instead of pip below
skip_install = True
passenv = RASCALINE_BUILD_TYPE

deps =
    discover

commands =
    python setup.py --quiet install
    discover -p "*.py" -s python/tests
"""
