[package]
name = "rascaline"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
edition = "2018"

[[bench]]
name = "spherical-harmonics"
harness = false

[[bench]]
name = "soap-radial-integral"
harness = false

[dependencies]
ndarray = "0.13"
nalgebra = "0.24"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
num-traits = "0.2"
indexmap = "1.6"
log = "0.4"

[dev-dependencies]
approx = "0.4"
# TODO: this is licensed under GPL-v3
GSL = "3.0"
criterion = "0.3"
